export const FEACH_RELATED_DATA_INIT = 'FEACH_RELATED_DATA_INIT';
export const FEACH_RELATED_DATA_SUCESS = 'FEACH_RELATED_DATA_SUCESS';
export const FEACH_RELATED_DATA_FAILURE = 'FEACH_RELATED_DATA_FAILURE';
