export const FEACH_AVAILABLE_FIELD_INIT = 'FEACH_AVAILABLE_FIELD_INIT';
export const FEACH_AVAILABLE_FIELD_SUCESS = 'FEACH_AVAILABLE_FIELD_SUCESS';
export const FEACH_AVAILABLE_FIELD_FAILURE = 'FEACH_AVAILABLE_FIELD_FAILURE';

export const ADD_SELECTED_COLUMN_LIST = 'ADD_SELECTED_COLUMN_LIST';
